### ISSUE TITLE
'Map loading...'

### ISSUE THREAD

**Issue by mhenden** [sunnysideup/silverstripe-googlemapbasic#3]
It isn't.

I have module loaded, works in CMS, have requested and set up API key, etc but map is simply NOT loading. Did I miss anything?

**Comment by sunnysideup** [comment]
hey MIke

I would love to get it working for you.  I will have a quick look for you and see what I can do.

Have you looked at the error (e.g. is it a JS error you are getting or something else?)

Cheers

Nicolaas

**Comment by sunnysideup** [comment]
Hi @mhenden 

I ran a composer install of googlemapbasic and it worked nicely - out of the box:

![image](https://cloud.githubusercontent.com/assets/167154/5713978/5a540062-9b27-11e4-8d3e-37b952c98f80.png)

**Comment by sunnysideup** [comment]
Please let me know if you need more help.  We are also available for paid support and development.

**Comment by sunnysideup** [comment]
I think the first thing you need to find out is why it is not working.  Did you add \

```html
    <% include GoogleMapBasic %>
```
to your Page.ss?

**Comment by sunnysideup** [comment]
what version are you using ?

are you sure it is not googlemaps?

**Comment by mhenden** [comment]
Hi Nicholaas, not getting a JS error or any other sort of error -- weirdest thing is that it's working fine in local environment but won't work on the live site! It just sits there telling me it's 'loading'...

**Comment by sunnysideup** [comment]
OK - if you sure that the code is identical then I would look at (a) permissions for files (b) ?flush=all - solves MOST problems (c) database differences ... maybe the address you have entered on the live site is not recognised by Google... .

**Comment by mhenden** [comment]
Should add that I have used silverstripe-googlemap on another site -- couldn't get it workin in localhost development on this one which is why I looked at googlemapbasic... which, as I said, DID work!

**Comment by sunnysideup** [comment]
well, I have both modules working on several live sites, just let me know if you need help.  I can also provide assistance @ NZD75 per hour.  If you dont have any specific issues then it is hard to help you much further on this bug.

**Comment by mhenden** [comment]
Thanks Nicholaas -- have made a bit of progress. Changed permissions on directory to 777 and I have been able to load a map -- as an image (can't load a dynamic map which is what I had here? Any clues?

**Comment by sunnysideup** [comment]
I would validate your html, and double-check for JS errors (F12).

**Comment by mhenden** [comment]
OK, have just produced a JS error (as seen in FireBug): 

TypeError: GoogleMapBasic.SET_infoWindowContent is not a function
	GoogleMapBasic.SET_infoWindowContent("\x3cdiv class=\"infoWindowContent typograp...

Afraid it doesn't mean that much to me... any tips?

**Comment by sunnysideup** [comment]
that means, the JS file is probably not included.

**Comment by mhenden** [comment]
Back again Nicholaas! You're right, the JS file wasn't included (thought this happened automatically as it had in development environment). I added a 'Requirements::' link to Page.php and it loaded. Went through to google.apis, etc and I thought it was going to work. But still no map, just  a blank space where a map should be ('Map loading...' disappeared) -- and no error showing in Firebug... 

And my HomePage inagel slider disappeared as well... obviously conflicting with map JS...

**Comment by sunnysideup** [comment]
would you like me to have a look at it?  you can PM me: nt @ sunny zide up

**Comment by sunnysideup** [comment]
as in www.sunnysideup.co.nz

**Comment by mhenden** [comment]
Still checking things out -- now seeing the error in local environment. Map still works though?!

Error: Syntax error, unrecognized expression: .$MapID
	throw new Error( "Syntax error, unrecognized expression: " + msg );

**Comment by mhenden** [comment]
Just saw your other message Nicholaas -- how long do you think you would need to fix?

**Comment by mhenden** [comment]
Weird. Javascript is loading on live site -- goes and looks at Google.APIs and then returns no map. But if I save map as static image I get the following: 

ReferenceError: google is not defined
	geocoder = new google.maps.Geocoder();

**Comment by sunnysideup** [comment]
it will definitely take less than an hour to fix.

**Comment by mhenden** [comment]
Hi Nicholaas -- just had a thought -- if GoogleMapBasic is working fine in local site (which it is) but not on live server, could it be a server setting that is stopping it? I've talked to my hosting company who have confirmed that all server ports apart from the standard http and https (80 and 443) are blocked. Could this be what is stopping map form displaying (as I said page is communicating with google APIs, etc...)?

**Comment by sunnysideup** [comment]
Hi Mike 

I really dont know, sounds unlikely.  If you are happy to pay up to NZD75 then I can help you.  Right now, I simply dont have enough information and it works on your local host and so if all settings are the same it should work on your server.

**Comment by sunnysideup** [comment]
If you are keen for me to help you then please email me and I will send you invoice.  Once that is paid, I will assist you until it works!
